/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Return all completed submissions for the authenticated user and event_code.
         */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Submissions
         * @description Return all completed submissions for the authenticated user across all events.
         */
        get: operations["get_all_submissions_api_account_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Permanently delete the authenticated user and all their submissions.
         */
        delete: operations["delete_account_api_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Platform-wide statistics.
         */
        get: operations["get_stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Time-series analytics for the last 30 days.
         */
        get: operations["get_analytics_api_admin_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all registered users with their submission count.
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Submissions
         * @description Get all submissions for a specific user.
         */
        get: operations["get_user_submissions_api_admin_users__user_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Simple health check — confirms the server is up without hitting the DB.
         */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pdf
         * @description Upload a PDF for grading. Returns a job_id to poll for results.
         */
        post: operations["upload_pdf_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Poll job status and get results when complete.
         */
        get: operations["get_job_status_api_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Get available event clusters and their specific events.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Rubric
         * @description Create or update a rubric. Admin-only — this can overwrite grading criteria.
         */
        post: operations["create_rubric_api_rubrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics/{event}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rubric
         * @description Get a specific rubric by event name. Admin-only.
         */
        get: operations["get_rubric_api_rubrics__event__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIDetectionResult */
        AIDetectionResult: {
            /** Score */
            score: number;
            /**
             * Sentence Scores
             * @default []
             */
            sentence_scores: components["schemas"]["SentenceAIScore"][];
        };
        /** AdminAnalytics */
        AdminAnalytics: {
            /** Signups 30D */
            signups_30d: components["schemas"]["DailyDataPoint"][];
            /** Submissions 30D */
            submissions_30d: components["schemas"]["DailyDataPoint"][];
            /** Anon Submissions 30D */
            anon_submissions_30d: components["schemas"]["DailyDataPoint"][];
            /** Auth Submissions 30D */
            auth_submissions_30d: components["schemas"]["DailyDataPoint"][];
        };
        /** AdminStats */
        AdminStats: {
            /** Total Users */
            total_users: number;
            /** Total Submissions */
            total_submissions: number;
            /** Submissions Today */
            submissions_today: number;
            /** Submissions This Week */
            submissions_this_week: number;
            /** Unique Ips */
            unique_ips: number;
            /** Anonymous Submissions */
            anonymous_submissions: number;
            /** Authenticated Submissions */
            authenticated_submissions: number;
            /** Completion Rate */
            completion_rate: number;
            /** Top Events */
            top_events: components["schemas"]["TopEvent"][];
        };
        /** AdminSubmissionRow */
        AdminSubmissionRow: {
            /** Job Id */
            job_id: string;
            /** Event Name */
            event_name: string;
            /** Event Code */
            event_code?: string | null;
            /** Total Awarded */
            total_awarded?: number | null;
            /** Total Possible */
            total_possible?: number | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** AdminUserRow */
        AdminUserRow: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Picture */
            picture?: string | null;
            /** Created At */
            created_at: string;
            /** Submission Count */
            submission_count: number;
        };
        /** Body_upload_pdf_api_upload_post */
        Body_upload_pdf_api_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Event Code */
            event_code: string;
        };
        /** ClusterEvents */
        ClusterEvents: {
            /** Cluster Name */
            cluster_name: string;
            /** Display Label */
            display_label: string;
            /** Events */
            events: components["schemas"]["EventInfo"][];
        };
        /** DailyDataPoint */
        DailyDataPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /** EventInfo */
        EventInfo: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** GradingResult */
        GradingResult: {
            /** Event Name */
            event_name: string;
            /** Total Possible */
            total_possible: number;
            /** Total Awarded */
            total_awarded: number;
            /** Sections */
            sections: components["schemas"]["SectionScore"][];
            /** Overall Feedback */
            overall_feedback: string;
            /**
             * Penalties
             * @default []
             */
            penalties: components["schemas"]["PenaltyCheck"][];
            /**
             * Was Truncated
             * @default false
             */
            was_truncated: boolean;
            /** Truncated At Tokens */
            truncated_at_tokens?: number | null;
            /**
             * Graded By
             * @default openai
             */
            graded_by: string;
            ai_detection?: components["schemas"]["AIDetectionResult"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Job Id */
            job_id: string;
            /** Event Name */
            event_name: string;
            /** Event Code */
            event_code?: string | null;
            /** Total Awarded */
            total_awarded: number;
            /** Total Possible */
            total_possible: number;
            /** Created At */
            created_at: string;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "complete" | "failed";
            result?: components["schemas"]["GradingResult"] | null;
            /** Error */
            error?: string | null;
            /** Event Code */
            event_code?: string | null;
        };
        /** PenaltyCheck */
        PenaltyCheck: {
            /** Description */
            description: string;
            /** Penalty Points */
            penalty_points: number;
            /**
             * Status
             * @enum {string}
             */
            status: "flagged" | "clear" | "manual_check";
            /** Note */
            note: string;
        };
        /** RubricCreate */
        RubricCreate: {
            /** Event Name */
            event_name: string;
            rubric_data: components["schemas"]["RubricSchema"];
        };
        /** RubricSchema */
        RubricSchema: {
            /** Event */
            event: string;
            /** Total Points */
            total_points: number;
            /** Required Outline */
            required_outline?: Record<string, never> | null;
            /** Sections */
            sections: components["schemas"]["RubricSection"][];
        };
        /** RubricSection */
        RubricSection: {
            /** Name */
            name: string;
            /** Max Points */
            max_points: number;
            /** Description */
            description: string;
            /** Scoring Guide */
            scoring_guide?: {
                [key: string]: string;
            };
        };
        /** SectionScore */
        SectionScore: {
            /** Name */
            name: string;
            /** Max Points */
            max_points: number;
            /** Awarded Points */
            awarded_points: number;
            /** Feedback */
            feedback: string;
            /** Improvement */
            improvement?: string | null;
        };
        /** SentenceAIScore */
        SentenceAIScore: {
            /** Sentence */
            sentence: string;
            /** Score */
            score: number;
        };
        /** TopEvent */
        TopEvent: {
            /** Event Code */
            event_code: string;
            /** Count */
            count: number;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Job Id */
            job_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_history_api_history_get: {
        parameters: {
            query: {
                /** @description Event code to filter submissions */
                event_code: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_submissions_api_account_submissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_account_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_admin_analytics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_submissions_api_admin_users__user_id__submissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_pdf_api_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdf_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterEvents"][];
                };
            };
        };
    };
    create_rubric_api_rubrics_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rubric_api_rubrics__event__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
